title: little diary
description: collection of tid bits, small projects and thoughts
theme: null
markdown: kramdown
highlighter: rouge
url: "https://gurki.github.io"
baseurl: "/little-diary"
kramdown:
  input: GFM
  syntax_highlighter: rouge