title: little diary 📔
description: collection of tid bits, small projects and thoughts
theme: null
markdown: GFM
highlighter: rouge
url: "https://gurki.github.io"
baseurl: "/little-diary"
page_excerpts: true
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-last-modified-at
last-modified-at:
  date-format: "%Y-%m-%dT%H:%M:%SZ"